### PR TITLE
Fix sample Nighscout URL to end with a "/"

### PR DESCRIPTION
**Pull request by mhaeberli**
I found that, at least in my case, this made it work where it wasn't before.

@mddub - thanks for your great work!

### CODE REVIEW

**Comment by mddub** [comment]
Thanks! I'm surprised that was necessary, since it's supposed to be [stripped of a trailing slash](https://github.com/mddub/urchin-cgm/blob/9b7b165/config/js/config.js#L345) before being sent to the watch, and is [assumed to have no trailing slash](https://github.com/mddub/urchin-cgm/blob/3f5bc7/src/js/data.js#L599) elsewhere. I know it seems trivial, but some other Nightscout watchfaces I've seen are particularly finicky about URL formats, resulting in some excruciating support conversations, so I'd like to avoid adding copy which even implies that the code is so particular.

Would you mind double-checking that it wasn't another (perhaps distinct/more serious) issue before I merge this?

**Comment by mhaeberli** [comment]
Mark,
I'd be happy to - although I don't quite know how... - I tried without the
slash - it failed; I added ONLY the slash, it succeeded ...
Suggestions welcome.
Best,
Martin

**Comment by mddub** [comment]
Thanks. Not trying to diagnose the issue here, just want to confirm that you've tried those steps a second time and still experience the problem?

If so, I'll merge this. And in that case, it would be super helpful if you can send me the Pebble logs from your phone (in the Pebble app, go to "Support", then "Contact support", then "Other", then enter any message, then change the recipient address to `mark@warkmilson.com` and send).

**Comment by mhaeberli** [comment]
I'll send you the pebble logs.
But my attempts to reproduce failed.
so go ahead and close the request ... as spurious.  sorry.

**Comment by mhaeberli** [comment]
one thing I haven't tried is uninstalling the app and re-installing it.

I promise it didn't work yesterday until I put the / in; but the slash
clearly is not persisted ... and it works without ...

**Comment by mddub** [comment]
I've seen transient issues with Nightscout; could have been that. Please open an issue if you see something strange again. Thanks!

**Pull request closed without merging**
