### PR TITLE
display raw nightscout data

### PR DESCRIPTION
**Pull request by mgranberry**
This looks like it should work, but it isn't showing up in the config menu.  Am I missing something?  As far as I can tell the JavaScript isn't changing at all when I run `pebble build;pebble install`, but it could be something more subtle.

### CODE REVIEW

**Comment by mddub** [comment]
This is great. Did you try `BUILD_ENV=development pebble build`? Otherwise, you'll see the github.io config page when you `pebble emu-app-config`.

https://github.com/mddub/nightscout-graph-pebble#testing-the-configuration-page

**Comment by mgranberry** [comment]
Yep.  That was most of the problem.  There were a couple problems with the code too, so I'll have a change soon.  I'm getting raw data now, though, I just have to back out some changes I made while tracking down my error.  :)

**Comment by mgranberry** [comment]
I think this is ready to go now.

**Comment by francesc0-cgm** [comment]
On my pebble time steel it runs but i can't get in setting screen

**Comment by mddub** [comment]
Yep, looks great. @francesc0-cgm, this hadn't yet been merged into a release, but it's ready now. Let us know how it works in #2.

**Pull request merged**
