### PR TITLE
Sdk3 path graph

### PR DESCRIPTION
**Pull request by mgranberry**
I am playing around with this continuous graph vs. the discrete points.  I've tried to make it clean enough to merge, but it will make automated testing more difficult, so no hard feelings if this doesn't go anywhere.  I'd also be open to adding a config option.

pebble_screenshot_2015-12-05_20-46-51

### CODE REVIEW

**Comment by mgranberry** [comment]
Apples to apples:
pebble_screenshot_2015-12-05_22-20-40
pebble_screenshot_2015-12-05_22-21-21

Actually that's interesting.  It looks like I need to fix the light-weight dot line.  I'll fix that and update the PR.

**Comment by mgranberry** [comment]
pebble_screenshot_2015-12-05_22-27-56
Fixed.

**Comment by mgranberry** [comment]
When doing thought (and some code) experiments for a watch face that I was planning, I considered creating a PDC on the phone and pushing it to the Pebble in a message.  The PDC allows sub-pixel accuracy for points, which might be nice in a more compact display such as one where a larger time area showed dates or more pump status.

**Comment by mddub** [comment]
Looks good to me! One thing that jumps out is that the final point needs to make more obvious contact with the right edge of the graph; otherwise my brain is telling me there's missing data, so the "recency is obvious from the graph" heuristic breaks down.

As for automated testing, I don't mind running it through both aplite and basalt. Hopefully I'll get a chance to add screenshot diffing soon, so the process won't rely on manual inspection. At that point, the more coverage, the better. Have you tried running this through the `test/do_screenshots.sh` flow? For now you'll have to change `test/util.py` to [make it run on basalt](https://github.com/mddub/nightscout-graph-pebble/blob/cadda2/test/util.py#L31). I'm wondering how missing points will look; the fixed-width square points make it easy to see the extent of missing data.

**Comment by mddub** [comment]
Yeah, it could be very cool to create the PDC on the phone. My biggest concern is that you can't manipulate the graph on the Pebble to indicate when you lose phone connectivity, or accurately render the staleness of cached data when switching back to the watchface. Keeping all the staleness logic on the Pebble has made things easy to reason about, too. It may be worth sacrificing that for the flexibility of doing more in JS, like a log scale, dynamic bounds, and colors.

One quick win when the graph is more compact is choosing point width/height dynamically based on the bounds. Exposing layout options in the configuration page is the Very Next Big Feature, and then it will definitely be worth playing with some layout test cases to see where and how the graph can be made to look better.

**Comment by mgranberry** [comment]
You're right about the margin issue.  I'm just not sure how to extend the last few pixels.  Gaps work fine, but it needs to be over a bit more.  Any suggestions?

**Comment by mgranberry** [comment]
I could always shift the x coords over one and double the initial reading.

**Comment by mgranberry** [comment]
It turns out that nothing fancy needed to happen.  The collection-of-rects drawing addresses the left-most part of the box, while the path addresses the right-most point.  Changing `GRAPH_POINT_SIZE * (1 + i + padding)` to `GRAPH_POINT_SIZE * (i + padding)` fixes everything.

**Comment by mddub** [comment]
I personally prefer the collection-of-rects, but if you want it, I'm happy to include this as an option in the config page. I ran through the test suite and found two issues:

http://attorney-tailors-81503.bitballoon.com/basalt-not-smooth/screenshots.html
http://attorney-tailors-81503.bitballoon.com/basalt-smooth/screenshots.html

TestErrorCodes - points not showing up when there are discontinuities
TestTrimmingValues - looks like the y values are higher by 1 pixel (this could well be the result of a bug in my code, whose assumptions you're relying on)

I made a couple fixes to get tests running under Basalt. I still have to clean the tests up a bit to automagically run against both platforms, but for now you can override [this line](https://github.com/mddub/nightscout-graph-pebble/blob/5847f7/test/util.py#L31) to get the same output as I gave above.

(Yay tests!)

**Comment by mgranberry** [comment]
I'm in the process of debugging Pebble's emu-app-config.  It hasn't worked for me since I experimented with some websocket clients.  I think I got a broken version installed.

I think the off-by-one-pixel problem is because the rectangles are specifying the edge of a region vs. the center of a line, which for a 3-pixel-wide line will be one pixel.  The missing points are a problem because a single point doesn't specify much of a line.  I'll have to think about what the right solution is to that because it isn't immediately apparent what the right thing to do is when there isn't any data.  Maybe isolated points should be small circles.  The other option is to interpolate a line, but I hate to imply data that isn't there.

**Pull request closed without merging**
